### ISSUE TITLE
Bitte Matrix zusätzlich zu Slack supporten.

### ISSUE THREAD

**Issue by JokerGermany** [evcc-io/evcc.io#23]
Wäre klasse wenn ihr den Nutzern die Wahl lassen wollen, ob sie ein freies oder ein proprietäres Protocol nutzen wollen.

Wäre cool wenn ihr Slack mit Matrix bridgen würdet:
https://ems-docs.element.io/books/element-cloud-documentation/page/public-slack-bridge

Es gab schon Räume die mit dem evcc Slack gebridged wurden, diese funktioniert aber seit dem 11. März nicht mehr.
https://matrix.to/#/#evcc-io-random:matrix.org
https://matrix.to/#/#evcc-io:matrix.org
Das Problem an diesen Räumen war allerdings, dass nicht die Moderation-Tools von Matrix (z.B. https://tchncs.de/matrix#bots ) genutzt wurden, was unnötigen spam verursacht hat.

**Comment by premultiply** [comment]
Haben wir gerade erst wegen Spam entfernt.

**Comment by JokerGermany** [comment]
Der Spam wäre nicht da mit einer anständigen Moderations-Bot wie eben https://tchncs.de/matrix#bots
Schade das es nirgends erwähnt wurde, dann hätte ich helfen können =(

**Comment by andig** [comment]
Wir haben kein Matrix. Und damit auch kein Spam. Danke.

**Comment by JokerGermany** [comment]
Okay, danke war schön mit euch zu sprechen im Slack. =)

Wünsche euch viel Spaß bis ihr irgendwann wieder eine offene Plattform unterstützt.

**Comment by frzifus** [comment]
> Haben wir gerade erst wegen Spam entfernt.

Das kann ich verstehen. Ich denke, eines der Hauptprobleme war, dass ich der einzige Admin war und eine Zeit lang inaktiv war. Somit gab also keinerlei Moderation.

Leider habe ich den Spam erst sehr spät (als @JokerGermany mich darauf hin gewiesen hatte) bemerkt. Aktuell ist `@anti-scam:matrix.org` im channel aktiviert.

> Wir haben kein Matrix. Und damit auch kein Spam. Danke.

Was sehr schade ist. Für mich ist es nicht nachvollziehbar, warum man nach der Aktivierung von Anti-Spam das Problem nicht löst, indem man 2-3 Personen Moderationsrechte auf Matrix-Org gibt und das Ganze noch einmal probiert.
Dies führt nur zum Ausschluss von Personen, welche sich nicht bei einem fragwürdigen Massenger wie Slack anzumelden möchten.

**Comment by andig** [comment]
Gibts denn einen konkreten Vorschlag wie ein Spam-freies evcc Matrix aussehen würde?
