### ISSUE TITLE
Hardware recommendation

### ISSUE THREAD

**Issue by rmeyer85** [evcc-io/evcc.io#27]
Hi, currently I'm using evcc as an addon in HA but unfortunately my hardware is working at limit because I have just a raspberry pi 4 with 1gb ram. Therefore I'm looking for a new hardware solution:-) Now I'm not sure what is the best way to use both HA and evcc. 

First option is to buy a mini pc with more power to install HA and the evcc as an addon.
Second option is to buy a second raspberry pi or a HA green so that I can use evcc on the old raspberry pi and HA on HA green.

What is your recommendation? I mean to read multiple times that it is better to use evcc as a stand alone app on a appropiate hardware. In this case it is better to have 2 independent hardware systems.

Thanks in advance :-)

**Comment by naltatis** [comment]
@rmeyer85 your question is better located in our discussions: https://github.com/evcc-io/evcc/discussions

In short: evcc is not resource hungry. A Raspeberry Pi Zero 2 should be powerful enough. If you want to also run other software on the same hardware its heavily depends on what you're doing.
