### ISSUE TITLE
"maxCurrent" cannot be set over MQTT

### ISSUE THREAD

**Issue by SpectrixPvP** [evcc-io/evcc.io#30]
When publishing e.g. _14_ to the MQTT topic _evcc/loadpoints/1/maxCurrent/set_, the _Max. Current_ within the settings of the loadpoint in the UI is not updating. 
In another evcc installation (version 0.127.1) this is working. 

Note: This is related to the Home Assistant Add-on of evcc.

**Comment by andig** [comment]
Unfortunately your report is missing a detailed log file. Without log, we don‘t have the information for diagnosing the issue described. See https://docs.evcc.io/docs/faq#wie-kann-ich-ein-logfile-zur-fehleranalyse-erstellen.
