### ISSUE TITLE
Non workink link

### ISSUE THREAD

**Issue by petrsykora** [evcc-io/evcc.io#32]
Non workink link from https://evcc.io/en/ to https://docs.evcc.io/en/docs/devices/chargers/. 
![obrazek](https://github.com/user-attachments/assets/bd2b962a-f22c-4997-a25f-977ca2ea3253)
![obrazek](https://github.com/user-attachments/assets/4ab7c34f-43c8-4a83-a588-b30f73bc0ea4)

**Comment by naltatis** [comment]
@petrsykora Is fixed. Thanks for reporting 🙌
